### PR TITLE
Implement gulp and minification

### PR DESCRIPTION
**Pull request by Costava**
Build and minify using gulp.

The minified scripts are given a `.min.js` extension and placed in the same directory.

Issue #9: "Implement Uglifier/Minifier"
Issue #10: "Implement Gulp"

### CODE REVIEW

**Comment by pranaygp** [comment]
Hey @Costava thanks for taking up both these issues. The only concern I have is that the gulpfile you wrote currently only works on the specified files. While this works for now, I'd like to have them run on those directories instead ( `src` and `specs` ) to keep stuff modular in the future.

**Comment by Costava** [comment]
@pranaygp Sounds good. Will fix.

**Comment by Costava** [comment]
@pranaygp Fixed it. Let me know if anything is still not right.

**Comment by pranaygp** [comment]
@Costava thanks for helping out :) . I also took the liberty of throwing both the minified files into git ( 9627a506078a3ca7bba5a9129b0e51a0bdf1a2d6 ) and merged your PR

**Pull request merged**
